# Generated by Django 2.1.1 on 2018-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('node_count', models.IntegerField(default=3)),
            ],
        ),
    ]
